### ISSUE TITLE
Not enough horizontal spacing on main nav

### ISSUE THREAD

**Issue by allisonwill** [city-mechanical/city-mechanical-website#24]
when viewing main nav @ certain browser widths nav buttons are squished and arrow stacks on top and it doesnt fit properly. (looks very very bad) 

Browsers this is known to occur on:
- [ ]  Google Chrome
- [X]  Firefox
- [X] Safari
- [X] Opera
- [ ] Microsoft Edge
- [ ] Internet Explorer

**Comment by CrutchTheClutch** [comment]
This is now happening again on select devices
